// Generated by CoffeeScript 1.8.0
(function() {
  var app, bodyParser, express, http, jsonpack, log, methodOverride, path, util;

  http = require('http');

  express = require('express');

  jsonpack = require('jsonpack');

  bodyParser = require('body-parser');

  methodOverride = require('method-override');

  path = require('path');

  util = require('util');

  log = require('./lib/log').logger;

  app = express();

  http.createServer(app).listen(app.get('port', function(req, res) {
    return log.info(util.format('Server listening on port %s', app.get('port')));
  }));

}).call(this);

//# sourceMappingURL=server.js.map
